name: new-cg-idps
dependencies:
  - python
  - jinja2
  - matplotlib
  - notebook
  - numpy
  - openpyxl
  - pandas
  - scikit-learn
  - scipy
  - xlrd
  - cython
  - pip
  - conda-forge::hoomd
  - conda-forge::openmm
  - conda-forge::mdtraj
  - conda-forge::mdanalysis
  - pip:
    - biopython
    - ray
    - PeptideBuilder
    - DEERPREdict
